<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\WifiPackage;
use App\Models\Subscription;
use Illuminate\Database\Seeder;

class QuickSubscriptionSeeder extends Seeder
{
    public function run()
    {
        // 1. Ensure a Package exists
        $package = WifiPackage::firstOrCreate(
            ['name' => 'Family Stream 20 Mbps'],
            [
                'speed' => '20 Mbps',
                'price' => 250000,
                'description' => 'Ideal untuk streaming keluarga',
                'is_active' => true
            ]
        );

        // 2. Find the test user (assuming the last created customer or specific email)
        // We'll try to find 'user@example.com' or just pick the latest customer
        $user = User::where('email', 'user@example.com')->first();
        
        if (!$user) {
            $user = User::where('role', 'customer')->latest()->first();
        }

        if (!$user) {
            $this->command->info("No customer found. Creating one.");
            $user = User::create([
                'name' => 'Test User',
                'email' => 'user@example.com',
                'password' => bcrypt('password'),
                'role' => 'customer',
                'status' => 'active'
            ]);
        }

        // 3. Create Subscription
        $sub = Subscription::create([
            'user_id' => $user->id,
            'wifi_package_id' => $package->id,
            'installation_address' => 'Jl. Merdeka No. 45, Jakarta',
            'status' => 'active',
            'installation_date' => now()->subDays(10),
            'activated_at' => now()->subDays(9),
            'notes' => 'Generated by QuickSubscriptionSeeder'
        ]);

        $this->command->info("Subscription created for user: {$user->email}");
    }
}
